### ISSUE TITLE
Complete the database round trips

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect#26]
Organizations, Priorities, Events/actions all need real round trips in the components

**Comment by kelfink** [comment]
Organizations search pulls from the API, as of https://github.com/code4sac/neighborhood-connect/pull/32. which needs reviews

**Comment by ryanmdoyle** [comment]
I'm closing this for the more specific issue of #58 which has the remaining POST requests that need to work by the 31st.  Currently, we are waiting on the backend API team to finish those.
