### ISSUE TITLE
Show all the organizations on org list until search input filters it

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect#45]
The placeholder in the org list is by design, but we need to update it.  Until we have a map built, or something much better than a list of organizations to draw from, it is easier for users to see all existing organizations until they filter them.  If they hav Eno idea what neighborhood to select, they can at least scroll through all neighborhoods, this way.

**Comment by Kaleidics** [comment]
Branch fix-search-margins fixes this, but removes the placeholder from image. That is ok?
