### ISSUE TITLE
Current neighborhood does not show on the priorities page

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect#46]
There should always be a neighborhood selected when we are on the priorities page.  It needs to show on this page, per designs

**Comment by ryanmdoyle** [comment]
I think someone else was working on this page? Currently the api route just needs to be changed. 

Should the default view show all priorities, with no neighborhood selected? Or should we have a default neighborhood?

**Comment by ryanmdoyle** [comment]
The PrioritiesPage will immediately reroute to select a neighborhood if none is selected.

**Comment by ryanmdoyle** [comment]
Fixed with #54
