### ISSUE TITLE
Events page should have a link back to the associated priorities list

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect#47]
Add a link somewhere on the Events list page that takes us back to the priorities page

**Comment by ryanmdoyle** [comment]
We actually need a few back buttons throughout, maybe something similar to the current button in the upper right, but it floats in the upper left?  We can pass routes and text to it, similar to the one on the right.

**Comment by Kaleidics** [comment]
I have added a button that redirects to "/". Not sure if this is the correct implementation. But it works for now. Please check the latest branch "multiple-styling-updates" for this change.

**Comment by ryanmdoyle** [comment]
Fix on #57
