### ISSUE TITLE
Add css styling on the Add New Event page

### ISSUE THREAD

**Issue by kelfink** [code4sac/neighborhood-connect#48]
Currently there's no styling.  It should follow the designs and be consistent with the rest of the app

**Comment by Kaleidics** [comment]
I have added tentative styling to this page. There isn't a mockup design for this in the AdobeXD files. May need to consult the designers? Or wing it for now?

**Comment by ryanmdoyle** [comment]
Hey @Kaleidics not sure if you were working on this more, but the styles could also be applied to the New Priority Form. I just did a PR for that with #69.

**Comment by Kaleidics** [comment]
I think I already added styles to the forms. There's only NewActionForm and NewPriorityForm right?

**Comment by ryanmdoyle** [comment]
Yes
